global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'capitole-sisu-products'
    static_configs:
      - targets: ['capitole-sisu-products:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
