spring:
  application:
    name: products-api
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    user: sa
    password:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100, expireAfterWrite=10m
  messages:
    basename: messages
    encoding: UTF-8
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    root: INFO
    com:
      capitole:
        payments: INFO
